services:
  ubuntu_one:
    build:
      context: ./ubuntu1
    container_name: ubuntu_one
    command: bash -c "while true; do sleep 3600; done"

  ubuntu_two:
    build:
      context: ./ubuntu2
    container_name: ubuntu_two
    command: bash -c "while true; do sleep 3600; done"
